# Generated by Django 4.2.4 on 2023-08-24 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='first_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='sexo',
            new_name='sex',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='tipo_usuario',
            new_name='user_type',
        ),
    ]
