# Generated by Django 4.2.4 on 2023-08-25 14:55

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_rename_primeiro_nome_usuario_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='birth_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cpf_cnpj',
            field=models.CharField(default=django.utils.timezone.now, max_length=14, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
