# Generated by Django 4.2.1 on 2023-08-27 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_birth_date_usuario_cpf_cnpj_usuario_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='first_name',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
