# Generated by Django 4.2.1 on 2023-09-03 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_usuario_email'),
        ('usuarios', '0006_usuario_created_at_usuario_updated_at_and_more'),
    ]

    operations = [
    ]
