# Generated by Django 4.2.1 on 2023-10-01 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_merge_20230903_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='last_name',
            field=models.CharField(default='teste', max_length=25),
            preserve_default=False,
        ),
    ]
