# Generated by Django 4.2.1 on 2023-10-05 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_alter_usuario_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cpf_cnpj',
            field=models.CharField(default='', max_length=14, unique=True),
        ),
    ]
