# Generated by Django 4.2.4 on 2023-08-24 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laboratorio',
            old_name='name',
            new_name='nome',
        ),
    ]
