# Generated by Django 4.2.4 on 2023-08-24 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorios', '0002_rename_name_laboratorio_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laboratorio',
            old_name='sobre',
            new_name='about',
        ),
        migrations.RenameField(
            model_name='laboratorio',
            old_name='nome',
            new_name='name',
        ),
    ]
