# Generated by Django 4.2.4 on 2023-09-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorios', '0006_laboratorio_created_at_laboratorio_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratorio',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
