# Generated by Django 4.2.1 on 2023-10-04 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorios', '0007_laboratorio_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratorio',
            name='about',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
