# Generated by Django 4.2.1 on 2023-10-07 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorios', '0010_laboratorio_is_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratorio',
            name='price',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10),
            preserve_default=False,
        ),
    ]
