# Generated by Django 4.2.1 on 2023-10-08 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorios', '0012_alter_laboratorio_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratorio',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=25.0, max_digits=10, null=True),
        ),
    ]
