# Generated by Django 4.2.1 on 2023-10-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorios', '0013_alter_laboratorio_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratorio',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
