# Generated by Django 4.2.4 on 2023-08-25 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorios', '0004_laboratorio_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservas', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='laboratorio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='laboratorios.laboratorio'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
