# Generated by Django 4.2.4 on 2023-08-25 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_alter_reserva_laboratorio_alter_reserva_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='laboratorio',
            new_name='laboratory',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='usuario',
            new_name='user',
        ),
    ]
