# Generated by Django 4.2.1 on 2023-09-03 12:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_rename_laboratorio_reserva_laboratory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='booked_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
