# Generated by Django 4.2.4 on 2023-10-06 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorios', '0010_laboratorio_is_booked'),
        ('reservas', '0007_reserva_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='laboratory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratorios.laboratorio'),
        ),
    ]
