# Generated by Django 4.2.1 on 2023-11-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0011_alter_reserva_booking_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='started',
            field=models.BooleanField(default=True),
        ),
    ]
